# The general principle for this config file is the following:
#
#     Our configuration file is composed of one entry per module,
#     with the key being the module name. We also have one special
#     entry where we store the default configuration used for all
#     module. The default configuration is stored under the special
#     module named '*'.
#
#     When looking for a specific configuration, we first
#     look at the entry in the module's section. If not found,
#     then we take the default configuration instead.
#
#     Next, we look in the module's section for an entry whose name
#     is the name of the configuration with a '+' at the front.
#     Eg, if we are looking for the "copyright" configuration
#     for that module, search also for "+copyright". Unlike
#     the entry with the option name, this entry does not
#     override the default option, it adds to it.

# Default configuration, applying to all modules by default.

'*':
    # A description of how copyright headers are expected to be.
    # Repository-specific configurations can override part or
    # all of this config.
    #
    # Repositories wishing to augment one or more of the entries
    # providing data as a list (rather than completely override it)
    # can do so by providing a "+<key>" entry where "<key>" is
    # the name of the key to be augmented.
    copyright_header_info:
        # The list of valid copyright holders (a list of strings);
        # One entry per valid copyright holder.
        holders:
            - AdaCore
            - Altran Praxis
            - Altran UK Limited
            - Free Software Foundation, Inc.
            - AdaCore, Altran Praxis
            - AdaCore and Altran UK Limited
            - AdaCore, Altran UK Limited
            - AdaCore and Altran UK
            - AdaCore, Altran UK
            # Altran UK has changed their name to Capgemini Engineering,
            # so add them as valid copyright holders as well (V103-009).
            - Capgemini Engineering
            - AdaCore, Capgemini Engineering

        # The maximum number of lines the tool will be scanning until
        # it finds a copyright line.
        max_lines: 24

        # A list of template strings telling the user what format
        # the copyright line should follow. This strings are there
        # to help the user write a correctly formed copyright holder
        # by providing templates of what the copyright line should
        # look like. The style_checker will just print each string
        # followed by a '<copyright holder>' placeholder.
        #
        # Each string must include a '%(year)d' placeholder that
        # the style_checker will replace with the current year.
        format_help:
            - 'Copyright (C) 1992-%(year)d, '

        # A list of regular expressions detecting what looks like
        # a copyright line. That copyright line may or may not be
        # correctly formed however.
        #
        # The purpose of having this as a list is to make it easier
        # to provide multiple alternatives without to code those
        # alternatives into one single regular expression.
        present_re:
            - 'copyright.*[0-9][0-9][0-9][0-9]'

        # A list of regular expressions matching a correctly formed copyright
        # line.
        #
        # In addition to validating a copyright line as being correctly
        # formed, each regular expression needs to define two groups
        # that need to be accessible by name. These groups are:
        #
        #   - 'year': A group that matches the copyright end year.
        #         For instance, if the copyright year range was 2014-2016,
        #         then the 'year' group would match '2016'.
        #   - 'holder': The string containing the copyright holder.
        #         For instance, if the copyright line looked like this...
        #
        #             Copyright (C) 2014-2016, Free Software Foundation
        #
        #         ... then the 'holder' group would be matching the string
        #         'Free Software Foundation'
        #
        #         Note that, should the copyright header be "boxed"
        #         (with comment markers both at the start and the end
        #         of the line), this regular expression does not need
        #         to worry about excluding the closing edge of the box.
        #
        # The purpose of having this as a list is to make it easier
        # to provide multiple alternatives without to code those
        # alternatives into one single regular expression.
        copyright_re:
            - ' *(--|\*|//|@c|%)? *(Copyright) \(C\) ([0-9][0-9][0-9][0-9]-)?(?P<year>[0-9][0-9][0-9][0-9]), (?P<holder>.*[^ */-])'

# Module-specific configuration.  This configuration is applied
# on top of the default configuration.

'examples':
    style_checks:
        - -copyright

'java':
    style_checks:
        - gnatx
